apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-federation
  labels:
    app: module-federation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: module-federation
  template:
    metadata:
      labels:
        app: module-federation
    spec:
      containers:
      - name: module-federation
        image: my-dockerhub-username/module-federation:latest
        ports:
        - containerPort: 80