name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "us-east-1"
      SECRET_ARN: arn:aws:secretsmanager:us-east-1:377147527660:secret:/prod/angular-module-federation

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get secrets from AWS Secrets Manager
        id: secrets
        run: |
          secret_name="/prod/angular-module-federation"
          secrets=$(aws secretsmanager get-secret-value --secret-id $secret_name --query SecretString --output text)
          
          echo "$secrets" > secrets.json
          echo "ECR_REPOSITORY=$(jq -r '.ECR_REPOSITORY' secrets.json)" >> $GITHUB_ENV
          echo "S3_BUCKET_NAME=$(jq -r '.S3_BUCKET_NAME' secrets.json)" >> $GITHUB_ENV
          echo "CLOUDFRONT_DISTRIBUTION_ID=$(jq -r '.CLOUDFRONT_DISTRIBUTION_ID' secrets.json)" >> $GITHUB_ENV

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v3
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      # - name: Log in to Amazon ECR
      #   run: |
      #     aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: nakalissi/module-federation:latest
